### PR TITLE
fix null pointer offset UB

### PR DESCRIPTION
**Pull request by mlugg**
This was being caught by ubsan on fontconfig init which made me very sad
so i changed it to make me very happy!

### CODE REVIEW

**Comment by mlugg** [comment]
I've just emailed this patch to upstream too

**Comment by mlugg** [comment]
patch fixified, now ready for review

**Comment by slimsag** [comment]
If I merge this as-is, then running [update-upstream.sh](https://github.com/hexops/freetype/blob/main/update-upstream.sh) would wipe out these changes.

If these changes are merged upstream, then we can update to use a `master` revision of freetype for now. @alichraghi can you help with this?

**Comment by mlugg** [comment]
It's been merged upstream as of the other day, see https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/207 - the fix there was actually done differently since I was informed of a macro that existed for this very purpose. So updating to upstream now would work :)

**Comment by alichraghi** [comment]
We should update to latest untagged commit. i'll diff changes

**Comment by alichraghi** [comment]
OK, i checked freetype for changes. there's nothing to add or change since https://github.com/freetype/freetype/commit/de8f14a8e41bf5e01714539cbcd3de16d546ce6c (latest commit). @mlugg, update `update-upstream.sh` to checkout into last commit.
```diff
-- git clone --depth 1 --branch VER-2-12-1 https://github.com/freetype/freetype
++ git clone --depth 1 https://github.com/freetype/freetype
git clone --depth 1 --branch 4.3.0 https://github.com/harfbuzz/harfbuzz
git clone --depth 1 --branch v1.0.9 https://github.com/google/brotli

# --- FreeType ---
pushd freetype/
++ git checkout de8f14a8e41bf5e01714539cbcd3de16d546ce6c
ft_delete=($(find -maxdepth 1 | grep -v -E '^./(builds|include|src|LICENSE\.TXT)$'))
```
run it and go to `hexops/mach` and update `libs/freetype/upstream` with 
```sh
git submodule update --remote --rebase libs/freetype/upstream
git add libs/freetype/upstream
git commit -m '<msg>'
```

**Comment by mlugg** [comment]
Closed in favor of #8

**Pull request closed without merging**
